### ISSUE TITLE
Typos & problems with Fr location

### ISSUE THREAD

**Issue by Prometheos2** [rugk/awesome-emoji-picker#40]
Introduction in English
![image](https://user-images.githubusercontent.com/45640841/58530298-3b413d00-81ac-11e9-81c3-15c582d0cbea.png)

and anomalous "les" 
![image](https://user-images.githubusercontent.com/45640841/58530312-498f5900-81ac-11e9-996a-4c65280014d5.png)

will do a PR when I have time

**Comment by rugk** [comment]
Yeah, please note the page on AMO may be outdated and I may have fixed some things already, so the files in this repo are the reference.
But feel free to proof-read it.

**Comment by Prometheos2** [comment]
Weirdly enough, I don't see where the bug comes from.

**Comment by rugk** [comment]
Yeah, I've already fixed the first line likely. (just not yet uploaded to AMO) The French grammar thing at the bottom is likely still unfixed however.

**Comment by rugk** [comment]
BTW change should be live on AMO now. :smiley:

**Comment by Prometheos2** [comment]
> BTW change should be live on AMO now. smiley

Unless I didn't fix the problem, no, it's not 😰

**Comment by rugk** [comment]
Wait, what? :open_mouth:

**Comment by Prometheos2** [comment]
It still have the same text on the add-on option screen
![image](https://user-images.githubusercontent.com/45640841/58829743-95138e00-8616-11e9-9879-03493c5c155a.png)
![image](https://user-images.githubusercontent.com/45640841/58829747-9775e800-8616-11e9-80e5-5ac2242c33d7.png)

**Comment by rugk** [comment]
Okay, maybe it's just cached locally/saved at add-on installation. Online, it's certainly already updated: https://addons.mozilla.org/fr/firefox/addon/awesome-emoji-picker/

**Comment by Prometheos2** [comment]
There is still the grammar typo though 😕 (and an untranslated bit, mb 😥)
![image](https://user-images.githubusercontent.com/45640841/58830480-6696b280-8618-11e9-9ed6-6d5000cb4e18.png)

**Comment by rugk** [comment]
We like PRs, don't we? :stuck_out_tongue_winking_eye: 

And hey, you can do another change there as well then: https://github.com/rugk/awesome-emoji-picker/issues/27#issuecomment-498404281

**Comment by Prometheos2** [comment]
We love PR, but not plenty that are incomplete 🙁

I will see that later

**Comment by rugk** [comment]
Yeah, if I had a good translation platform, I would likely use it, but well… I've had trouble finding one that had excellent support for the i18n format WebExtensions use, see https://github.com/rugk/offline-qr-code/issues/6.
